name: Nightly Build for rolling

#on:
#  schedule:
#    - cron: '0 12 * * *'
#
#  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ros:rolling
      env:
        ROS_DISTRO: rolling
    steps:
      - name: Check out repository code
        uses: actions/checkout@main
        with:
          path: rolling_ws/src
      - name: Install dependencies
        shell: bash
        run: |
          apt update
          apt install -y ros-rolling-example-interfaces
      - name: Build
        shell: bash
        run: |
          source /opt/ros/rolling/setup.bash
          cd rolling_ws
          colcon build --symlink-install
      - name: Run tests
        shell: bash
        run: |
          source /opt/ros/rolling/setup.bash
          cd rolling_ws
          colcon test
